// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.27.5
// source: protocol/rpc/c2.proto

package rpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_protocol_rpc_c2_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_rpc_c2_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_protocol_rpc_c2_proto_rawDescGZIP(), []int{0}
}

type BeaconList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Beacons       []*BeaconInfo          `protobuf:"bytes,1,rep,name=beacons,proto3" json:"beacons,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BeaconList) Reset() {
	*x = BeaconList{}
	mi := &file_protocol_rpc_c2_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BeaconList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeaconList) ProtoMessage() {}

func (x *BeaconList) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_rpc_c2_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BeaconList.ProtoReflect.Descriptor instead.
func (*BeaconList) Descriptor() ([]byte, []int) {
	return file_protocol_rpc_c2_proto_rawDescGZIP(), []int{1}
}

func (x *BeaconList) GetBeacons() []*BeaconInfo {
	if x != nil {
		return x.Beacons
	}
	return nil
}

type BeaconInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Hostname      string                 `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Username      string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	Os            string                 `protobuf:"bytes,4,opt,name=os,proto3" json:"os,omitempty"`
	Arch          string                 `protobuf:"bytes,5,opt,name=arch,proto3" json:"arch,omitempty"`
	Interval      int64                  `protobuf:"varint,6,opt,name=interval,proto3" json:"interval,omitempty"`
	Jitter        int64                  `protobuf:"varint,7,opt,name=jitter,proto3" json:"jitter,omitempty"`
	LastCheckin   int64                  `protobuf:"varint,8,opt,name=last_checkin,json=lastCheckin,proto3" json:"last_checkin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BeaconInfo) Reset() {
	*x = BeaconInfo{}
	mi := &file_protocol_rpc_c2_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BeaconInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeaconInfo) ProtoMessage() {}

func (x *BeaconInfo) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_rpc_c2_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BeaconInfo.ProtoReflect.Descriptor instead.
func (*BeaconInfo) Descriptor() ([]byte, []int) {
	return file_protocol_rpc_c2_proto_rawDescGZIP(), []int{2}
}

func (x *BeaconInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *BeaconInfo) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *BeaconInfo) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *BeaconInfo) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *BeaconInfo) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

func (x *BeaconInfo) GetInterval() int64 {
	if x != nil {
		return x.Interval
	}
	return 0
}

func (x *BeaconInfo) GetJitter() int64 {
	if x != nil {
		return x.Jitter
	}
	return 0
}

func (x *BeaconInfo) GetLastCheckin() int64 {
	if x != nil {
		return x.LastCheckin
	}
	return 0
}

type TaskList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tasks         []*TaskInfo            `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskList) Reset() {
	*x = TaskList{}
	mi := &file_protocol_rpc_c2_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskList) ProtoMessage() {}

func (x *TaskList) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_rpc_c2_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskList.ProtoReflect.Descriptor instead.
func (*TaskList) Descriptor() ([]byte, []int) {
	return file_protocol_rpc_c2_proto_rawDescGZIP(), []int{3}
}

func (x *TaskList) GetTasks() []*TaskInfo {
	if x != nil {
		return x.Tasks
	}
	return nil
}

type TaskInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	ImplantId     string                 `protobuf:"bytes,2,opt,name=implant_id,json=implantId,proto3" json:"implant_id,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskInfo) Reset() {
	*x = TaskInfo{}
	mi := &file_protocol_rpc_c2_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskInfo) ProtoMessage() {}

func (x *TaskInfo) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_rpc_c2_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskInfo.ProtoReflect.Descriptor instead.
func (*TaskInfo) Descriptor() ([]byte, []int) {
	return file_protocol_rpc_c2_proto_rawDescGZIP(), []int{4}
}

func (x *TaskInfo) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskInfo) GetImplantId() string {
	if x != nil {
		return x.ImplantId
	}
	return ""
}

func (x *TaskInfo) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *TaskInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type CreateTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ImplantId     string                 `protobuf:"bytes,1,opt,name=implant_id,json=implantId,proto3" json:"implant_id,omitempty"`
	TaskType      string                 `protobuf:"bytes,2,opt,name=task_type,json=taskType,proto3" json:"task_type,omitempty"`
	Payload       string                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTaskRequest) Reset() {
	*x = CreateTaskRequest{}
	mi := &file_protocol_rpc_c2_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTaskRequest) ProtoMessage() {}

func (x *CreateTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_rpc_c2_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTaskRequest.ProtoReflect.Descriptor instead.
func (*CreateTaskRequest) Descriptor() ([]byte, []int) {
	return file_protocol_rpc_c2_proto_rawDescGZIP(), []int{5}
}

func (x *CreateTaskRequest) GetImplantId() string {
	if x != nil {
		return x.ImplantId
	}
	return ""
}

func (x *CreateTaskRequest) GetTaskType() string {
	if x != nil {
		return x.TaskType
	}
	return ""
}

func (x *CreateTaskRequest) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

type CreateTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTaskResponse) Reset() {
	*x = CreateTaskResponse{}
	mi := &file_protocol_rpc_c2_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTaskResponse) ProtoMessage() {}

func (x *CreateTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_rpc_c2_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTaskResponse.ProtoReflect.Descriptor instead.
func (*CreateTaskResponse) Descriptor() ([]byte, []int) {
	return file_protocol_rpc_c2_proto_rawDescGZIP(), []int{6}
}

func (x *CreateTaskResponse) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type GenerateImplantRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerUrl     string                 `protobuf:"bytes,1,opt,name=server_url,json=serverUrl,proto3" json:"server_url,omitempty"`
	PathPrefix    string                 `protobuf:"bytes,2,opt,name=path_prefix,json=pathPrefix,proto3" json:"path_prefix,omitempty"`
	Interval      int64                  `protobuf:"varint,3,opt,name=interval,proto3" json:"interval,omitempty"`
	Jitter        *int64                 `protobuf:"varint,4,opt,name=jitter,proto3,oneof" json:"jitter,omitempty"`
	Goos          string                 `protobuf:"bytes,5,opt,name=goos,proto3" json:"goos,omitempty"`
	Goarch        string                 `protobuf:"bytes,6,opt,name=goarch,proto3" json:"goarch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateImplantRequest) Reset() {
	*x = GenerateImplantRequest{}
	mi := &file_protocol_rpc_c2_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateImplantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateImplantRequest) ProtoMessage() {}

func (x *GenerateImplantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_rpc_c2_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateImplantRequest.ProtoReflect.Descriptor instead.
func (*GenerateImplantRequest) Descriptor() ([]byte, []int) {
	return file_protocol_rpc_c2_proto_rawDescGZIP(), []int{7}
}

func (x *GenerateImplantRequest) GetServerUrl() string {
	if x != nil {
		return x.ServerUrl
	}
	return ""
}

func (x *GenerateImplantRequest) GetPathPrefix() string {
	if x != nil {
		return x.PathPrefix
	}
	return ""
}

func (x *GenerateImplantRequest) GetInterval() int64 {
	if x != nil {
		return x.Interval
	}
	return 0
}

func (x *GenerateImplantRequest) GetJitter() int64 {
	if x != nil && x.Jitter != nil {
		return *x.Jitter
	}
	return 0
}

func (x *GenerateImplantRequest) GetGoos() string {
	if x != nil {
		return x.Goos
	}
	return ""
}

func (x *GenerateImplantRequest) GetGoarch() string {
	if x != nil {
		return x.Goarch
	}
	return ""
}

type GenerateImplantResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Digest        string                 `protobuf:"bytes,1,opt,name=digest,proto3" json:"digest,omitempty"`
	Binary        []byte                 `protobuf:"bytes,2,opt,name=binary,proto3" json:"binary,omitempty"`
	Filename      string                 `protobuf:"bytes,3,opt,name=filename,proto3" json:"filename,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateImplantResponse) Reset() {
	*x = GenerateImplantResponse{}
	mi := &file_protocol_rpc_c2_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateImplantResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateImplantResponse) ProtoMessage() {}

func (x *GenerateImplantResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_rpc_c2_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateImplantResponse.ProtoReflect.Descriptor instead.
func (*GenerateImplantResponse) Descriptor() ([]byte, []int) {
	return file_protocol_rpc_c2_proto_rawDescGZIP(), []int{8}
}

func (x *GenerateImplantResponse) GetDigest() string {
	if x != nil {
		return x.Digest
	}
	return ""
}

func (x *GenerateImplantResponse) GetBinary() []byte {
	if x != nil {
		return x.Binary
	}
	return nil
}

func (x *GenerateImplantResponse) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

type TaskResultRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskResultRequest) Reset() {
	*x = TaskResultRequest{}
	mi := &file_protocol_rpc_c2_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskResultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskResultRequest) ProtoMessage() {}

func (x *TaskResultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_rpc_c2_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskResultRequest.ProtoReflect.Descriptor instead.
func (*TaskResultRequest) Descriptor() ([]byte, []int) {
	return file_protocol_rpc_c2_proto_rawDescGZIP(), []int{9}
}

func (x *TaskResultRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type TaskResultResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	ImplantId     string                 `protobuf:"bytes,3,opt,name=implant_id,json=implantId,proto3" json:"implant_id,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	Error         string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	Output        string                 `protobuf:"bytes,6,opt,name=output,proto3" json:"output,omitempty"`
	Completed     string                 `protobuf:"bytes,7,opt,name=completed,proto3" json:"completed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskResultResponse) Reset() {
	*x = TaskResultResponse{}
	mi := &file_protocol_rpc_c2_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskResultResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskResultResponse) ProtoMessage() {}

func (x *TaskResultResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_rpc_c2_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskResultResponse.ProtoReflect.Descriptor instead.
func (*TaskResultResponse) Descriptor() ([]byte, []int) {
	return file_protocol_rpc_c2_proto_rawDescGZIP(), []int{10}
}

func (x *TaskResultResponse) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskResultResponse) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *TaskResultResponse) GetImplantId() string {
	if x != nil {
		return x.ImplantId
	}
	return ""
}

func (x *TaskResultResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *TaskResultResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *TaskResultResponse) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *TaskResultResponse) GetCompleted() string {
	if x != nil {
		return x.Completed
	}
	return ""
}

var File_protocol_rpc_c2_proto protoreflect.FileDescriptor

const file_protocol_rpc_c2_proto_rawDesc = "" +
	"\n" +
	"\x15protocol/rpc/c2.proto\x12\bxhc2.rpc\"\a\n" +
	"\x05Empty\"<\n" +
	"\n" +
	"BeaconList\x12.\n" +
	"\abeacons\x18\x01 \x03(\v2\x14.xhc2.rpc.BeaconInfoR\abeacons\"\xcf\x01\n" +
	"\n" +
	"BeaconInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\x12\x0e\n" +
	"\x02os\x18\x04 \x01(\tR\x02os\x12\x12\n" +
	"\x04arch\x18\x05 \x01(\tR\x04arch\x12\x1a\n" +
	"\binterval\x18\x06 \x01(\x03R\binterval\x12\x16\n" +
	"\x06jitter\x18\a \x01(\x03R\x06jitter\x12!\n" +
	"\flast_checkin\x18\b \x01(\x03R\vlastCheckin\"4\n" +
	"\bTaskList\x12(\n" +
	"\x05tasks\x18\x01 \x03(\v2\x12.xhc2.rpc.TaskInfoR\x05tasks\"n\n" +
	"\bTaskInfo\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x1d\n" +
	"\n" +
	"implant_id\x18\x02 \x01(\tR\timplantId\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\"i\n" +
	"\x11CreateTaskRequest\x12\x1d\n" +
	"\n" +
	"implant_id\x18\x01 \x01(\tR\timplantId\x12\x1b\n" +
	"\ttask_type\x18\x02 \x01(\tR\btaskType\x12\x18\n" +
	"\apayload\x18\x03 \x01(\tR\apayload\"-\n" +
	"\x12CreateTaskResponse\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\"\xc8\x01\n" +
	"\x16GenerateImplantRequest\x12\x1d\n" +
	"\n" +
	"server_url\x18\x01 \x01(\tR\tserverUrl\x12\x1f\n" +
	"\vpath_prefix\x18\x02 \x01(\tR\n" +
	"pathPrefix\x12\x1a\n" +
	"\binterval\x18\x03 \x01(\x03R\binterval\x12\x1b\n" +
	"\x06jitter\x18\x04 \x01(\x03H\x00R\x06jitter\x88\x01\x01\x12\x12\n" +
	"\x04goos\x18\x05 \x01(\tR\x04goos\x12\x16\n" +
	"\x06goarch\x18\x06 \x01(\tR\x06goarchB\t\n" +
	"\a_jitter\"e\n" +
	"\x17GenerateImplantResponse\x12\x16\n" +
	"\x06digest\x18\x01 \x01(\tR\x06digest\x12\x16\n" +
	"\x06binary\x18\x02 \x01(\fR\x06binary\x12\x1a\n" +
	"\bfilename\x18\x03 \x01(\tR\bfilename\",\n" +
	"\x11TaskResultRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\"\xc4\x01\n" +
	"\x12TaskResultResponse\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x1d\n" +
	"\n" +
	"implant_id\x18\x03 \x01(\tR\timplantId\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error\x12\x16\n" +
	"\x06output\x18\x06 \x01(\tR\x06output\x12\x1c\n" +
	"\tcompleted\x18\a \x01(\tR\tcompleted2\xd9\x02\n" +
	"\x02C2\x124\n" +
	"\vListBeacons\x12\x0f.xhc2.rpc.Empty\x1a\x14.xhc2.rpc.BeaconList\x120\n" +
	"\tListTasks\x12\x0f.xhc2.rpc.Empty\x1a\x12.xhc2.rpc.TaskList\x12G\n" +
	"\n" +
	"CreateTask\x12\x1b.xhc2.rpc.CreateTaskRequest\x1a\x1c.xhc2.rpc.CreateTaskResponse\x12V\n" +
	"\x0fGenerateImplant\x12 .xhc2.rpc.GenerateImplantRequest\x1a!.xhc2.rpc.GenerateImplantResponse\x12J\n" +
	"\rGetTaskResult\x12\x1b.xhc2.rpc.TaskResultRequest\x1a\x1c.xhc2.rpc.TaskResultResponseB Z\x1exhc2_for_studying/protocol/rpcb\x06proto3"

var (
	file_protocol_rpc_c2_proto_rawDescOnce sync.Once
	file_protocol_rpc_c2_proto_rawDescData []byte
)

func file_protocol_rpc_c2_proto_rawDescGZIP() []byte {
	file_protocol_rpc_c2_proto_rawDescOnce.Do(func() {
		file_protocol_rpc_c2_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protocol_rpc_c2_proto_rawDesc), len(file_protocol_rpc_c2_proto_rawDesc)))
	})
	return file_protocol_rpc_c2_proto_rawDescData
}

var file_protocol_rpc_c2_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_protocol_rpc_c2_proto_goTypes = []any{
	(*Empty)(nil),                   // 0: xhc2.rpc.Empty
	(*BeaconList)(nil),              // 1: xhc2.rpc.BeaconList
	(*BeaconInfo)(nil),              // 2: xhc2.rpc.BeaconInfo
	(*TaskList)(nil),                // 3: xhc2.rpc.TaskList
	(*TaskInfo)(nil),                // 4: xhc2.rpc.TaskInfo
	(*CreateTaskRequest)(nil),       // 5: xhc2.rpc.CreateTaskRequest
	(*CreateTaskResponse)(nil),      // 6: xhc2.rpc.CreateTaskResponse
	(*GenerateImplantRequest)(nil),  // 7: xhc2.rpc.GenerateImplantRequest
	(*GenerateImplantResponse)(nil), // 8: xhc2.rpc.GenerateImplantResponse
	(*TaskResultRequest)(nil),       // 9: xhc2.rpc.TaskResultRequest
	(*TaskResultResponse)(nil),      // 10: xhc2.rpc.TaskResultResponse
}
var file_protocol_rpc_c2_proto_depIdxs = []int32{
	2,  // 0: xhc2.rpc.BeaconList.beacons:type_name -> xhc2.rpc.BeaconInfo
	4,  // 1: xhc2.rpc.TaskList.tasks:type_name -> xhc2.rpc.TaskInfo
	0,  // 2: xhc2.rpc.C2.ListBeacons:input_type -> xhc2.rpc.Empty
	0,  // 3: xhc2.rpc.C2.ListTasks:input_type -> xhc2.rpc.Empty
	5,  // 4: xhc2.rpc.C2.CreateTask:input_type -> xhc2.rpc.CreateTaskRequest
	7,  // 5: xhc2.rpc.C2.GenerateImplant:input_type -> xhc2.rpc.GenerateImplantRequest
	9,  // 6: xhc2.rpc.C2.GetTaskResult:input_type -> xhc2.rpc.TaskResultRequest
	1,  // 7: xhc2.rpc.C2.ListBeacons:output_type -> xhc2.rpc.BeaconList
	3,  // 8: xhc2.rpc.C2.ListTasks:output_type -> xhc2.rpc.TaskList
	6,  // 9: xhc2.rpc.C2.CreateTask:output_type -> xhc2.rpc.CreateTaskResponse
	8,  // 10: xhc2.rpc.C2.GenerateImplant:output_type -> xhc2.rpc.GenerateImplantResponse
	10, // 11: xhc2.rpc.C2.GetTaskResult:output_type -> xhc2.rpc.TaskResultResponse
	7,  // [7:12] is the sub-list for method output_type
	2,  // [2:7] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_protocol_rpc_c2_proto_init() }
func file_protocol_rpc_c2_proto_init() {
	if File_protocol_rpc_c2_proto != nil {
		return
	}
	file_protocol_rpc_c2_proto_msgTypes[7].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protocol_rpc_c2_proto_rawDesc), len(file_protocol_rpc_c2_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protocol_rpc_c2_proto_goTypes,
		DependencyIndexes: file_protocol_rpc_c2_proto_depIdxs,
		MessageInfos:      file_protocol_rpc_c2_proto_msgTypes,
	}.Build()
	File_protocol_rpc_c2_proto = out.File
	file_protocol_rpc_c2_proto_goTypes = nil
	file_protocol_rpc_c2_proto_depIdxs = nil
}
