// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.27.5
// source: protocol/rpc/c2.proto

package rpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	C2_ListBeacons_FullMethodName     = "/xhc2.rpc.C2/ListBeacons"
	C2_ListTasks_FullMethodName       = "/xhc2.rpc.C2/ListTasks"
	C2_CreateTask_FullMethodName      = "/xhc2.rpc.C2/CreateTask"
	C2_GenerateImplant_FullMethodName = "/xhc2.rpc.C2/GenerateImplant"
	C2_GetTaskResult_FullMethodName   = "/xhc2.rpc.C2/GetTaskResult"
)

// C2Client is the client API for C2 service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type C2Client interface {
	ListBeacons(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*BeaconList, error)
	ListTasks(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*TaskList, error)
	CreateTask(ctx context.Context, in *CreateTaskRequest, opts ...grpc.CallOption) (*CreateTaskResponse, error)
	GenerateImplant(ctx context.Context, in *GenerateImplantRequest, opts ...grpc.CallOption) (*GenerateImplantResponse, error)
	GetTaskResult(ctx context.Context, in *TaskResultRequest, opts ...grpc.CallOption) (*TaskResultResponse, error)
}

type c2Client struct {
	cc grpc.ClientConnInterface
}

func NewC2Client(cc grpc.ClientConnInterface) C2Client {
	return &c2Client{cc}
}

func (c *c2Client) ListBeacons(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*BeaconList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BeaconList)
	err := c.cc.Invoke(ctx, C2_ListBeacons_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *c2Client) ListTasks(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*TaskList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TaskList)
	err := c.cc.Invoke(ctx, C2_ListTasks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *c2Client) CreateTask(ctx context.Context, in *CreateTaskRequest, opts ...grpc.CallOption) (*CreateTaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateTaskResponse)
	err := c.cc.Invoke(ctx, C2_CreateTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *c2Client) GenerateImplant(ctx context.Context, in *GenerateImplantRequest, opts ...grpc.CallOption) (*GenerateImplantResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenerateImplantResponse)
	err := c.cc.Invoke(ctx, C2_GenerateImplant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *c2Client) GetTaskResult(ctx context.Context, in *TaskResultRequest, opts ...grpc.CallOption) (*TaskResultResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TaskResultResponse)
	err := c.cc.Invoke(ctx, C2_GetTaskResult_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// C2Server is the server API for C2 service.
// All implementations must embed UnimplementedC2Server
// for forward compatibility.
type C2Server interface {
	ListBeacons(context.Context, *Empty) (*BeaconList, error)
	ListTasks(context.Context, *Empty) (*TaskList, error)
	CreateTask(context.Context, *CreateTaskRequest) (*CreateTaskResponse, error)
	GenerateImplant(context.Context, *GenerateImplantRequest) (*GenerateImplantResponse, error)
	GetTaskResult(context.Context, *TaskResultRequest) (*TaskResultResponse, error)
	mustEmbedUnimplementedC2Server()
}

// UnimplementedC2Server must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedC2Server struct{}

func (UnimplementedC2Server) ListBeacons(context.Context, *Empty) (*BeaconList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListBeacons not implemented")
}
func (UnimplementedC2Server) ListTasks(context.Context, *Empty) (*TaskList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListTasks not implemented")
}
func (UnimplementedC2Server) CreateTask(context.Context, *CreateTaskRequest) (*CreateTaskResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateTask not implemented")
}
func (UnimplementedC2Server) GenerateImplant(context.Context, *GenerateImplantRequest) (*GenerateImplantResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerateImplant not implemented")
}
func (UnimplementedC2Server) GetTaskResult(context.Context, *TaskResultRequest) (*TaskResultResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTaskResult not implemented")
}
func (UnimplementedC2Server) mustEmbedUnimplementedC2Server() {}
func (UnimplementedC2Server) testEmbeddedByValue()            {}

// UnsafeC2Server may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to C2Server will
// result in compilation errors.
type UnsafeC2Server interface {
	mustEmbedUnimplementedC2Server()
}

func RegisterC2Server(s grpc.ServiceRegistrar, srv C2Server) {
	// If the following call pancis, it indicates UnimplementedC2Server was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&C2_ServiceDesc, srv)
}

func _C2_ListBeacons_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(C2Server).ListBeacons(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: C2_ListBeacons_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(C2Server).ListBeacons(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _C2_ListTasks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(C2Server).ListTasks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: C2_ListTasks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(C2Server).ListTasks(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _C2_CreateTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(C2Server).CreateTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: C2_CreateTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(C2Server).CreateTask(ctx, req.(*CreateTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _C2_GenerateImplant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateImplantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(C2Server).GenerateImplant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: C2_GenerateImplant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(C2Server).GenerateImplant(ctx, req.(*GenerateImplantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _C2_GetTaskResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskResultRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(C2Server).GetTaskResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: C2_GetTaskResult_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(C2Server).GetTaskResult(ctx, req.(*TaskResultRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// C2_ServiceDesc is the grpc.ServiceDesc for C2 service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var C2_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "xhc2.rpc.C2",
	HandlerType: (*C2Server)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListBeacons",
			Handler:    _C2_ListBeacons_Handler,
		},
		{
			MethodName: "ListTasks",
			Handler:    _C2_ListTasks_Handler,
		},
		{
			MethodName: "CreateTask",
			Handler:    _C2_CreateTask_Handler,
		},
		{
			MethodName: "GenerateImplant",
			Handler:    _C2_GenerateImplant_Handler,
		},
		{
			MethodName: "GetTaskResult",
			Handler:    _C2_GetTaskResult_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protocol/rpc/c2.proto",
}
